In [1]:
import pandas as pd

In [3]:
df=pd.read_csv("financial_dataset1.csv")

In [4]:
df

,Transaction_ID,Customer_ID,Customer_Name,Category,Sales,Profit,Quantity,Payment_Status,City,Transaction_Date
0,11317,CUST1134,Anjali,Furniture,1875.0,4126.0,16,Pending,Mumbai,2026-10-21 00:00:00
1,11001,CUST1177,Sneha,Stationery,32521.0,9290.0,13,Paid,Bangalore,2026-05-16 00:00:00
2,11069,CUST1478,Sneha,food,8948.0,8683.0,3,Unpaid,Chennai,2026-06-19 00:00:00
3,11968,CUST1016,Priya,Furniture,20072.0,8320.0,1,Pending,Mumbai,2027-09-11 12:00:00
4,10530,CUST1321,Priya,Stationery,32943.0,9336.0,3,Paid,Bangalore,2025-09-22 12:00:00
...,...,...,...,...,...,...,...,...,...,...
1995,10700,CUST1427,Rahul,Electronics,14407.0,9016.0,8,paid,Bangalore,2025-12-16 12:00:00
1996,11500,CUST1136,Neha,Electronics,2105.0,5292.0,13,Unpaid,Delhi,2027-01-20 12:00:00
1997,11706,CUST1247,Vivek,Food,35927.0,2756.0,5,Pending,Mangalore,2027-05-03 12:00:00
1998,10511,CUST1299,Rahul,Furniture,48447.0,1654.0,7,Unpaid,Delhi,2025-09-13 00:00:00
1999,11083,CUST1075,Arun,Clothing,8433.0,4718.0,5,Pending,Kochi,2026-06-26 00:00:00

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction_ID    2000 non-null   int64
 1   Customer_ID       2000 non-null   object
 2   Customer_Name     2000 non-null   object
 3   Category          1977 non-null   object
 4   Sales             1967 non-null   float64
 5   Profit            1970 non-null   float64
 6   Quantity          2000 non-null   int64
 7   Payment_Status    2000 non-null   object
 8   City              1979 non-null   object
 9   Transaction_Date  2000 non-null   object
dtypes: float64(2), int64(2), object(6)
memory usage: 156.4+ KB

In [7]:
df.head()

,Transaction_ID,Customer_ID,Customer_Name,Category,Sales,Profit,Quantity,Payment_Status,City,Transaction_Date
0,11317,CUST1134,Anjali,Furniture,1875.0,4126.0,16,Pending,Mumbai,2026-10-21 00:00:00
1,11001,CUST1177,Sneha,Stationery,32521.0,9290.0,13,Paid,Bangalore,2026-05-16 00:00:00
2,11069,CUST1478,Sneha,food,8948.0,8683.0,3,Unpaid,Chennai,2026-06-19 00:00:00
3,11968,CUST1016,Priya,Furniture,20072.0,8320.0,1,Pending,Mumbai,2027-09-11 12:00:00
4,10530,CUST1321,Priya,Stationery,32943.0,9336.0,3,Paid,Bangalore,2025-09-22 12:00:00

In [8]:
df.tail()

,Transaction_ID,Customer_ID,Customer_Name,Category,Sales,Profit,Quantity,Payment_Status,City,Transaction_Date
1995,10700,CUST1427,Rahul,Electronics,14407.0,9016.0,8,paid,Bangalore,2025-12-16 12:00:00
1996,11500,CUST1136,Neha,Electronics,2105.0,5292.0,13,Unpaid,Delhi,2027-01-20 12:00:00
1997,11706,CUST1247,Vivek,Food,35927.0,2756.0,5,Pending,Mangalore,2027-05-03 12:00:00
1998,10511,CUST1299,Rahul,Furniture,48447.0,1654.0,7,Unpaid,Delhi,2025-09-13 00:00:00
1999,11083,CUST1075,Arun,Clothing,8433.0,4718.0,5,Pending,Kochi,2026-06-26 00:00:00

In [9]:
df.describe()

       Transaction_ID         Sales        Profit    Quantity
count     2000.000000   1967.000000   1970.000000  2000.00000
mean     11001.443500  25147.046263   3469.098985    10.18850
std        578.772536  14375.624741   4923.386360     5.52958
min      10001.000000    516.000000  -4982.000000     1.00000
25%      10502.750000  12723.500000   -812.500000     5.00000
50%      10998.500000  25200.000000   3526.000000    10.00000
75%      11504.250000  37545.000000   7711.250000    15.00000
max      12000.000000  49923.000000  11988.000000    19.00000

In [10]:
df.shape

(2000, 10)

In [11]:
df["Sales"]=df["Sales"].fillna(df["Sales"].mean())

In [13]:
df["Category"]=df["Category"].fillna(df["Category"].mode()[0])

In [14]:
df["City"]=df["City"].fillna(df["City"].mode()[0])

In [15]:
df["Profit"]=df["Profit"].fillna(df["Profit"].mean())

In [17]:
df.duplicated().sum()

np.int64(40)

In [18]:
df=df.drop_duplicates()

In [21]:
df["Category"] = df["Category"].str.strip().str.title()

C:\Users\sheikh safana ilyas\AppData\Local\Temp\ipykernel_4104\1095268906.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Category"] = df["Category"].str.strip().str.title()